### ISSUE TITLE
[appimage]: allow install appimage files over xdgurl

### ISSUE THREAD

**Issue by star-buck** [xdgurl/xdgurl#16]
instead of ocsclient, we could also add "Install"-type appimage.
Then when clicking on "Install", xdgurl downloads appimage file, puts it under ~home/.appimages and executes it once to register the .desktop-file.

The question is how to update appimage files without downloading again, then maybe only downloading delta of the two appimages and asking user to update?

**Comment by probonopd** [comment]
Before setting the executable bit, there should be some signature checking to ensure that the AppImage at least comes from where it claims to come from. This should be presented to the user.

For updating, run `appimageupdate` on the AppImage. It should update itself using binary deltas (some work on this would be required to make zsync_curl robust for servers which don't handle range requests properly).

**Comment by akiraohgaki** [comment]
OK, xdgurl got appimage installation.

* install-type: appimages
* install-location: $HOME/.appimages

@star-buck 
> executes it once to register the .desktop-file.

xdgurl is make appimage executable, but does not execute the appimage automatically.
Because automatic execution is a little bit danger, if appimage is virus/malware.

As alternative, user can open an install location from "Open" button on dialog when installation finished.

**Comment by probonopd** [comment]
I am working on `appimaged`, a tiny optional daemon that watches the system for AppImages and puts them into the menu.

**Comment by akiraohgaki** [comment]
@probonopd 
It's good news for us.
The appimaged daemon have a default watch directory?

**Comment by probonopd** [comment]
Currently [these](https://github.com/probonopd/appimagetool/blob/83e70ad25e92f6bd26a1b63c211b63611922aefd/appimaged.c#L175-L180), let me know if I should add more.

**Comment by akiraohgaki** [comment]
@probonopd 
If you have a plan to support macOS, I recommend add $HOME/Application folder to watchlist, it's an application folder per user on macOS.

And for any Linux/UNIX user, I suggest you to define a directory for appimages under $XDG_DATA_HOME(.local/share) directory, like this:

$HOME/.local/share/appimages

**Comment by probonopd** [comment]
No plans to support macOS right now. *BSD might come next.

Why would anyone hide away their apps in a location that is usually invisible? How would you delete an app in this hidden location?

**Comment by akiraohgaki** [comment]
@probonopd 
Because desktop system or something package manager can get appimage file from web-api and stored and manage the files, if directory specified.
Maybe you know plasmoid, nautilus scripts, and more desktop stuff are stored in .local/share directory.

**Comment by akiraohgaki** [comment]
@probonopd 
But you keep freely, we may simply follow the appimaged spec.

**Comment by probonopd** [comment]
I suggest to use `$HOME/bin` for now if that is OK for you.

**Comment by akiraohgaki** [comment]
OK of course.

**Comment by probonopd** [comment]
That has the advantage that appimaged can handle the signature checking as well :-)

**Comment by akiraohgaki** [comment]
install-type for appimages changed.

Removed install-type: appimages

New install-type: bin
New alias of install-type bin: appimage
That install-location: $HOME/bin

**Comment by star-buck** [comment]
testing here:
https://www.linux-apps.com/p/1154217/

**Comment by star-buck** [comment]
That install-location: $HOME/bin
I dont like that very much, it clutters the HOME.
It should be put into 
.appimages or .bin

So its hidden, but clear, like when installing e.g. webapps.

Another thing is we need is the app to be clicked and executed from XDGURL, so after downloading, xdgurl should ask if to properly "install the app", so it gets registered and shows up fine in menu.

Of course we STILL very much need the tool to handle uninstalling, upgrading etc. appimages, so this is what ocsclient is _urgently_ needed for next.

**Comment by probonopd** [comment]
> Of course we STILL very much need the tool to handle uninstalling, upgrading etc. appimages

Check appimaged: https://www.youtube.com/watch?v=ckKiDcRXWgE

**Comment by akiraohgaki** [comment]
@star-buck 
I have changed about install-type "bin" and "appimages".
These are different install location now.

install-type: bin
install-location: $HOME/bin

install-type: appimages
install-location: $HOME/.appimages

Is that OK?

**Comment by probonopd** [comment]
`$HOME/.local/bin` and `$HOME/bin` are good choices:
* On CentOS/RHEL and Fedora: When you login, the script `$HOME/.bash_profile` is executed and this script adds `$HOME/.local/bin:$HOME/bin` to your path.
* On Ubuntu: When you login, the script `$HOME/.profile` is executed and this script adds `PATH="$HOME/bin:$HOME/.local/bin"` to your path.

**Comment by akiraohgaki** [comment]
Since xdgurl 2.0.3, '$HOME/.local/bin' as install location of type 'bin'.

**Comment by akiraohgaki** [comment]
Close for now.
And we will watch growing up appimaged.
