### ISSUE TITLE
Publish xdgurl program

### ISSUE THREAD

**Issue by akiraohgaki** [xdgurl/xdgurl#3]
> lets make as many categories "Install" from
>
> kde-look.org
> gnome-look.org
> xfce-look.org
> cinnamon-look.org
> mate-look.org
>
> then add the program under our own store under Utilities:
> https://www.linux-apps.com/browse/cat/244/ord/latest/
>
> Then upload debian, rpm redhat and suse, arch, and source files?

**Comment by star-buck** [comment]
@akiraohgaki : please concentrate on small introduction video and publish program on linux-apps.com, so we can start making "install" buttons visible for everyone on thursday.

**Comment by akiraohgaki** [comment]
Already published https://www.linux-apps.com/p/1136805/
