### ISSUE TITLE
Please add some xdgurl screenshots to https://www.linux-apps.com/p/1136805/

### ISSUE THREAD

**Issue by lucasrunner** [xdgurl/xdgurl#31]
Right now this site looks kinda empty. It would be nice to add some screenshots there. Here is a few examples.
![screenshot from 2016-12-04 12-38-05](https://cloud.githubusercontent.com/assets/1749847/20866221/d330c5c4-ba1f-11e6-854d-623b153a15ad.png)
![screenshot from 2016-12-04 12-38-22](https://cloud.githubusercontent.com/assets/1749847/20866222/d337bf5a-ba1f-11e6-8d4b-f24037135a4a.png)
![screenshot from 2016-12-04 12-38-37](https://cloud.githubusercontent.com/assets/1749847/20866223/d33bf304-ba1f-11e6-816a-7f37a8e35b9f.png)

Another thing, please clean download page because there are almost 15 entries now.

**Comment by star-buck** [comment]
@akiraohgaki : can you update screenshots and also hide old files?

**Comment by akiraohgaki** [comment]
OK, I have added screenshots and archived old versions.
https://www.linux-apps.com/p/1136805/
