### ISSUE TITLE
cinnamon xdg_types

### ISSUE THREAD

**Issue by star-buck** [xdgurl/xdgurl#5]
Extensions: https://cinnamon-spices.linuxmint.com/extensions
Applets: https://cinnamon-spices.linuxmint.com/applets

We already got the desklets:
Desklets: https://cinnamon-spices.linuxmint.com/desklets

**Comment by akiraohgaki** [comment]
OK, supported.

* cinnamon_applets
* cinnamon_extensions

https://github.com/xdgurl/xdgurl/blob/development/NOTE.md#httpswwwcinnamon-lookorg
